### ISSUE TITLE
About Supported Devices

### ISSUE THREAD

**Issue by tri3ni** [senrust/pymcprotocol#13]
Hi, I would like to communicate with a Mitsubishi PLC (iQ-R) using pymcprotocol. In the process, I would like to read out the ZR (file register) value of the device. However, I am currently unable to read out the value using pymcprotocol.
I would appreciate it if you could support this.

**Comment by senrust** [comment]
Thank you very much for using pymcprotocol.
I will do my best to support your success.
First, ZR register is a bit different from other registers such as X or Y register.
R and ZR register are file registers, so you must pay attention when accessing them.
From MC protocol manual, it notes for R and ZR register

> ### Consideration when accessing file register 
> The file register specified to "Use File Register of Each Program" in "CPU Parameter" or "PLC parameter" of the CPU module cannot be accessed from external devices. 
> If the file register of the CPU module is consist of multiple blocks, use the device code of the serial number access method. 
> To specify the file register with the serial number access method, refer to the manual of CPU module.

So please check this setting at first. If you fails still, let me know.

**Comment by tri3ni** [comment]
Currently, ZR10 is read out in double-word using SLMP communication. We have created a program based on the contents written in the following reference document. The command used in the program is readrandom.
(Reference material: IQ -R SLMP Reference Manual, URL: https://dl.mitsubishielectric.co.jp/dl/fa/members/document/manual/plc/sh080931/sh080931p.pdf)
The program reads ZR10 without any problems, so I believe the settings are correct.
In the program I created, the program is complicated because it requires additional processing when reading double-word. However, I would like to use pymcprotocol if possible because it requires only one line.
I would like to know if there is anything else I need to check.

**Comment by senrust** [comment]
Thanks for your investigation.
Ok. I understood your situation.
Maybe this problem is pymcprotocol bug.
I don't have iQ-R PLC so I did not tested in for iQ-R. 
(SLMP for iQ-R is a little different from other PLC series, I just implemented from manual.)

Could you give me help to solve this problem?
I would like to know 2 points.
1. Can you read other common double-word device, such as D device by pycmprotocol?
2. When reading ZR device fails, what error number does pymcprotocol report?

I appreciate your support in advance.

**Comment by tri3ni** [comment]
For 1, D and W for word devices and X, Y, and M for bit devices are readable by pycmprotocol.

For 2, "0" is read out without any error in reading.

**Comment by senrust** [comment]
Thanks.
So you can read other devices.
For ZR device, pymcptorocol result and your program result is incorrect.
I investigate further. Please wait.

**Comment by senrust** [comment]
ZR device is Hex device. Meanwhile R device is decimal device.
Do you recognize this diffrenece?
Can you share your pymcprotocol program?
I would like to know what number of ZR register do you access.

**Comment by tri3ni** [comment]
I am looking for double word access to ZR10.
The program is as follows

import pymcprotocol
pymc3e = pymcprotocol.Type3E(plctype="iQ-R")
pymc3e.connect("192.168.3.128", 5011)
word_values, dword_values = pymc3e.randomread(word_devices=["ZR10", "ZR11"], dword_devices=["ZR10"])
print(word_values)
print(dword_values)

The result is as follows
[0,0]
[0]

**Comment by senrust** [comment]
Thanks.
Can you dump your program binary send data to iQ-R PLC to read ZR10 device?
I would like to compare pymcprotocol send data.

**Comment by tri3ni** [comment]
The data to be sent are as follows

data = [
    0x50,
    0x00,
    0x00,
    0xFF,
    0xFF,
    0x03,
    0x00,
    0x0C,
    0x00,
    0x10,
    0x00,
    0x03,
    0x04,
    0x00,
    0x00,
    0x00,
    0x01,
    0x0A,
    0x00,
    0x00,
    0xB0,
]

The following programs are used for sending and receiving.
Received data is written to "result". the value of ZR10 is val.

sock.send(bytes(data))
result = [int(i) for i in sock.recv(1024)]
val = result[11:]

**Comment by senrust** [comment]
Thanks.
ZR device is hex device.
So pymcprotocol interprets access to ZR10 is "ZR0x10", 
But your program accesses ZR10 as "ZR0x0A".
If you would like to access ZR0x0A register, please use this code.
```python
word_values, dword_values = pymc3e.randomread(dword_devices=["ZR0x0A"])
```
Unfortunately, pymcprotocol cannnot understand "dword_devices=["ZRA"]", 
you must insert "0x" if you want to access registeres which numbers has only alphabet in hexadecimal notation because pymcprotocol interpret access to ZRA register.
This is the worst design in pymcprotocol. Sorry...

**Comment by tri3ni** [comment]
I understand.
I used ["ZR0x0A"] and was able to read the correct value.

Thank you very much for your support
