### ISSUE TITLE
Maximum size of block when reading bits, float and integers

### ISSUE THREAD

**Issue by robertosilviu** [senrust/pymcprotocol#14]
Hi,

I'm not sure what is the limit of the block size that can be used when calling `batchread_wordunits` or `batchread_bitunits`. It should be related to the protocol itself but it is not so clear to me. Inside the method ` _encode_value`  you are doing the check of the size. Can you explain what is the logic behind? Or do you know which is the max block size that we can use in a single call? Thank you!

**Comment by senrust** [comment]
Thank you very much for using pymcprotocol!
From MC Protocol specification, the limit of the block size depends on PLC type.
<img width="473" alt="ScreenShot" src="https://github.com/senrust/pymcprotocol/assets/59913933/2ea65289-32a8-4771-9806-1657b96660ef">

 _encode_value  is just function to encode python value to protocol binary.
 You can investigate MC Ptorocol reference from here.
https://dl.mitsubishielectric.com/dl/fa/document/manual/plc/sh080008/sh080008ab.pdf

**Comment by robertosilviu** [comment]
Thank you for the explanation. I will check it. From what i know the maximum payload can be 4096 bytes. When using the method `randomread` the behavior is the same? What i would like to understand is the behavior when trying to read sparse registers and if there is a maximum size of "sparsity" for the registers in order to read multiple registers in a single request.  
I need to read multiple registers with a time constraint on the callback. With my plc one request requires 20ms and i'm trying to understand the reason behind this behavior and if there is some way to reduce it.

**Comment by senrust** [comment]
The maximunm payload in randomread command is 96 or 192 registers.
<img width="470" alt="image" src="https://github.com/senrust/pymcprotocol/assets/59913933/ee8f7a57-d69d-4b5a-9b00-560ef0c67b07">

Pymcprotocol cannot promise worst time for response because it uses TCP/IP which is not time sensitive.
From my opinion, if you want to get response as soon as possible, the number of registers you request should be small and only necessary.
In addition, if you want to keep  20ms strictly, you should not use pymcprotocol but use CC-Link IE or CC-LinkTSN modules.

**Comment by robertosilviu** [comment]
Thank you for you help! The problem with CC-Link is that i need to communicate with the plc using python or something similar.
