### ISSUE TITLE
Inquiry Regarding Timeout Error

### ISSUE THREAD

**Issue by 1skypark1** [senrust/pymcprotocol#15]
Hello senrust,

I hope this message finds you well. I am currently using pymcprotocol.Type3E for Ethernet communication between a PC and a PLC in my project. I have encountered an issue related to timeout errors when running my code using the "f5" shortcut in VSCode.

Below is a simplified snippet of the code:

import pymcprotocol

comm = pymcprotocol.Type3E()
comm.setaccessopt(commtype="binary")
comm._sock.settimeout(5)

// The following line works fine with Shift+Enter but causes a timeout error with f5
batchread_bitunits('M1000', 1)

When executing this code using Shift+Enter, I am able to obtain the expected output without any issues. However, when using the "f5" shortcut, a timeout error occurs specifically in the batchread_bitunits part.

I wanted to reach out to you to inquire whether there might be any known reasons or solutions for this behavior. Any insights or suggestions you could provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by senrust** [comment]
Thank you very much for using pymcprotocol.  
I am very sorry that I cannot help you because I have no idea why such incident happens.   

Default time out of pymcprotocol is 2 sec and timeout setting is transfered to PLC when you send command.
You changed scoket time out directly, but timeout setting of MCProtocol is still default value 2sec.  
I think this caused trouble.

Can you set socket timeout from setaccessopt(commtype="binary", timer_sec=5)?  
This means change MCProtocol time out to 5 sec and socket timeout to 6 sec.

I hope this solves well

**Comment by 1skypark1** [comment]
thank you for the reply.

I figured out what the problem was.
If the PLC is not reset or rebooted after parameter setting, the connection is abnormal.

After resetting several times, it worked normally.
